using Jvlink2Db.Core.Records;

namespace Jvlink2Db.Db.Postgres.Tests.Records;

internal static class SeBuilder
{
    public static Se Empty() => new()
    {
        RecordSpec = "SE",
        DataKubun = string.Empty,
        MakeDate = string.Empty,
        Year = string.Empty,
        MonthDay = string.Empty,
        JyoCD = string.Empty,
        Kaiji = string.Empty,
        Nichiji = string.Empty,
        RaceNum = string.Empty,
        Wakuban = string.Empty,
        Umaban = string.Empty,
        KettoNum = string.Empty,
        Bamei = string.Empty,
        UmaKigoCD = string.Empty,
        SexCD = string.Empty,
        HinsyuCD = string.Empty,
        KeiroCD = string.Empty,
        Barei = string.Empty,
        TozaiCD = string.Empty,
        ChokyosiCode = string.Empty,
        ChokyosiRyakusyo = string.Empty,
        BanusiCode = string.Empty,
        BanusiName = string.Empty,
        Fukusyoku = string.Empty,
        Reserved1 = string.Empty,
        Futan = string.Empty,
        FutanBefore = string.Empty,
        Blinker = string.Empty,
        Reserved2 = string.Empty,
        KisyuCode = string.Empty,
        KisyuCodeBefore = string.Empty,
        KisyuRyakusyo = string.Empty,
        KisyuRyakusyoBefore = string.Empty,
        MinaraiCD = string.Empty,
        MinaraiCDBefore = string.Empty,
        BaTaijyu = string.Empty,
        ZogenFugo = string.Empty,
        ZogenSa = string.Empty,
        IJyoCD = string.Empty,
        NyusenJyuni = string.Empty,
        KakuteiJyuni = string.Empty,
        DochakuKubun = string.Empty,
        DochakuTosu = string.Empty,
        Time = string.Empty,
        ChakusaCD = string.Empty,
        ChakusaCDP = string.Empty,
        ChakusaCDPP = string.Empty,
        Jyuni1c = string.Empty,
        Jyuni2c = string.Empty,
        Jyuni3c = string.Empty,
        Jyuni4c = string.Empty,
        Odds = string.Empty,
        Ninki = string.Empty,
        Honsyokin = string.Empty,
        Fukasyokin = string.Empty,
        Reserved3 = string.Empty,
        Reserved4 = string.Empty,
        HaronTimeL4 = string.Empty,
        HaronTimeL3 = string.Empty,
        ChakuUma =
        [
            new SeChakuUma(string.Empty, string.Empty),
            new SeChakuUma(string.Empty, string.Empty),
            new SeChakuUma(string.Empty, string.Empty),
        ],
        TimeDiff = string.Empty,
        RecordUpKubun = string.Empty,
        DMKubun = string.Empty,
        DMTime = string.Empty,
        DMGosaP = string.Empty,
        DMGosaM = string.Empty,
        DMJyuni = string.Empty,
        KyakusituKubun = string.Empty,
    };

    public static Se Sample(string raceNum = "11", string umaban = "05", string bamei = "テストホース", string time = "1325") =>
        Empty() with
        {
            DataKubun = "7",
            MakeDate = "20260331",
            Year = "2026",
            MonthDay = "0331",
            JyoCD = "06",
            Kaiji = "01",
            Nichiji = "08",
            RaceNum = raceNum,
            Wakuban = "3",
            Umaban = umaban,
            KettoNum = "2020100123",
            Bamei = bamei,
            SexCD = "1",
            Barei = "04",
            Time = time,
            KakuteiJyuni = "01",
            NyusenJyuni = "01",
            Honsyokin = "00040000",
            ChakuUma =
            [
                new SeChakuUma("2020100001", "ウマＡ"),
                new SeChakuUma("2020100002", "ウマＢ"),
                new SeChakuUma("2020100003", "ウマＣ"),
            ],
        };
}
